export const country = [
    {
        id: 1,
        name: "Afghanistan",
        flag: "🇦🇫",
        code: "AF",

    },
    {
        id: 2,
        name: "Åland Islands",
        flag: "🇦🇽",
        code: "AX",

    },
    {
        id: 3,
        name: "Albania",
        flag: "🇦🇱",
        code: "AL",
    },
    {
        id: 4,
        name: "Algeria",
        flag: "🇩🇿",
        code: "DZ",
    },
    {
        id: 5,
        name: "American Samoa",
        flag: "🇦🇸",
        code: "AS",
    },
    {
        id: 6,
        name: "Andorra",
        flag: "🇦🇩",
        code: "AD",
    },
    {
        id: 7,
        name: "Angola",
        flag: "🇦🇴",
        code: "AO",
    },
    {
        id: 8,
        name: "Anguilla",
        flag: "🇦🇮",
        code: "AI",
    },
    {
        id: 9,
        name: "Antarctica",
        flag: "🇦🇶",
        code: "AQ",
    },
    {
        id: 10,
        name: "Antigua and Barbuda",
        flag: "🇦🇬",
        code: "AG",
    },
    {
        id: 11,
        name: "Argentina",
        flag: "🇦🇷",
        code: "AR",
    },
    {
        id: 12,
        name: "Armenia",
        flag: "🇦🇲",
        code: "AM",
    },
    {
        id: 13,
        name: "Aruba",
        flag: "🇦🇼",
        code: "AW",
    },
    {
        id: 14,
        name: "Australia",
        flag: "🇦🇺",
        code: "AU",
    },
    {
        id: 15,
        name: "Austria",
        flag: "🇦🇹",
        code: "AT",
    },
    {
        id: 16,
        name: "Azerbaijan",
        flag: "🇦🇿",
        code: "AZ",
    },
    {
        id: 17,
        name: "Bahamas",
        flag: "🇧🇸",
        code: "BS",
    },
    {
        id: 18,
        name: "Bahrain",
        flag: "🇧🇭",
        code: "BH",
    },
    {
        id: 19,
        name: "Bangladesh",
        flag: "🇧🇩",
        code: "BD",
    },
    {
        id: 20,
        name: "Barbados",
        flag: "🇧🇧",
        code: "BB",
    },
    {
        id: 21,
        name: "Belarus",
        flag: "🇧🇾",
        code: "BY",
    },
    {
        id: 22,
        name: "Belgium",
        flag: "🇧🇪",
        code: "BE",
    },
    {
        id: 23,
        name: "Belize",
        flag: "🇧🇿",
        code: "BZ",
    },
    {
        id: 24,
        name: "Benin",
        flag: "🇧🇯",
        code: "BJ",
    },
    {
        id: 25,
        name: "Bermuda",
        flag: "🇧🇲",
        code: "BM",
    },
    {
        id: 26,
        name: "Bhutan",
        flag: "🇧🇹",
        code: "BT",
    },
    {
        id: 27,
        name: "Bolivia",
        flag: "🇧🇴",
        code: "BO",
    },
    {
        id: 28,
        name: "Bosnia and Herzegovina",
        flag: "🇧🇦",
        code: "BA",
    },
    {
        id: 29,
        name: "Botswana",
        flag: "🇧🇼",
        code: "BW",
    },
    {
        id: 30,
        name: "Bouvet Island",
        flag: "🇧🇻",
        code: "BV",
    },
    {
        id: 31,
        name: "Brazil",
        flag: "🇧🇷",
        code: "BR",
    },
    {
        id: 32,
        name: "British Indian Ocean Territory",
        flag: "🇮🇴",
        code: "IO",
    },
    {
        id: 33,
        name: "Brunei Darussalam",
        flag: "🇧🇳",
        code: "BN",
    },
    {
        id: 34,
        name: "Bulgaria",
        flag: "🇧🇬",
        code: "BG",
    },
    {
        id: 35,
        name: "Burkina Faso",
        flag: "🇧🇫",
        code: "BF",
    },
    {
        id: 36,
        name: "Burundi",
        flag: "🇧🇮",
        code: "BI",
    },
    {
        id: 37,
        name: "Cambodia",
        flag: "🇰🇭",
        code: "KH",
    },
    {
        id: 38,
        name: "Cameroon",
        flag: "🇨🇲",
        code: "CM",
    },
    {
        id: 39,
        name: "Canada",
        flag: "🇨🇦",
        code: "CA",
    },
    {
        id: 40,
        name: "Cape Verde",
        flag: "🇨🇻",
        code: "CV",
    },
    {
        id: 41,
        name: "Cayman Islands",
        flag: "🇰🇾",
        code: "KY",
    },
    {
        id: 42,
        name: "Central African Republic",
        flag: "🇨🇫",
        code: "CF",
    },
    {
        id: 43,
        name: "Chad",
        flag: "🇹🇩",
        code: "TD",
    },
    {
        id: 44,
        name: "Chile",
        flag: "🇨🇱",
        code: "CL",
    },
    {
        id: 45,
        name: "China",
        flag: "🇨🇳",
        code: "CN",
    },
    {
        id: 46,
        name: "Christmas Island",
        flag: "🇨🇽",
        code: "CX",
    },
    {
        id: 47,
        name: "Cocos (Keeling) Islands",
        flag: "🇨🇨",
        code: "CC",
    },
    {
        id: 48,
        name: "Colombia",
        flag: "🇨🇴",
        code: "CO",
    },
    {
        id: 49,
        name: "Comoros",
        flag: "🇰🇲",
        code: "KM",
    },
    {
        id: 50,
        name: "Congo",
        flag: "🇨🇬",
        code: "CG",
    },
    {
        id: 51,
        name: "Congo",
        flag: "🇨🇩",
        code: "CD",
    },
    {
        id: 52,
        name: "Cook Islands",
        flag: "🇨🇰",
        code: "CK",
    },
    {
        id: 53,
        name: "Costa Rica",
        flag: "🇨🇷",
        code: "CR",
    },
    {
        id: 54,
        name: "Cote d'Ivoire",
        flag: "🇨🇮",
        code: "CI",
    },
    {
        id: 55,
        name: "Croatia",
        flag: "🇭🇷",
        code: "HR",
    },
    {
        id: 56,
        name: "Cuba",
        flag: "🇨🇺",
        code: "CU",
    },
    {
        id: 57,
        name: "Cyprus",
        flag: "🇨🇾",
        code: "CY",
    },
    {
        id: 58,
        name: "Czech Republic",
        flag: "🇨🇿",
        code: "CZ",
    },
    {
        id: 59,
        name: "Denmark",
        flag: "🇩🇰",
        code: "DK",
    },
    {
        id: 60,
        name: "Djibouti",
        flag: "🇩🇯",
        code: "DJ",
    },
    {
        id: 61,
        name: "Dominica",
        flag: "🇩🇲",
        code: "DM",
    },
    {
        id: 62,
        name: "Dominican Republic",
        flag: "🇩🇴",
        code: "DO",
    },
    {
        id: 63,
        name: "Ecuador",
        flag: "🇪🇨",
        code: "EC",
    },
    {
        id: 64,
        name: "Egypt",
        flag: "🇪🇬",
        code: "EG",
    },
    {
        id: 65,
        name: "El Salvador",
        flag: "🇸🇻",
        code: "SV",
    },
    {
        id: 66,
        name: "Equatorial Guinea",
        flag: "🇬🇶",
        code: "GQ",
    },
    {
        id: 67,
        name: "Eritrea",
        flag: "🇪🇷",
        code: "ER",
    },
    {
        id: 68,
        name: "Estonia",
        flag: "🇪🇪",
        code: "EE",
    },
    {
        id: 69,
        name: "Ethiopia",
        flag: "🇪🇹",
        code: "ET",
    },
    {
        id: 70,
        name: "Falkland Islands (Malvinas)",
        flag: "🇫🇰",
        code: "FK",
    },
    {
        id: 71,
        name: "Faroe Islands",
        flag: "🇫🇴",
        code: "FO",
    },
    {
        id: 72,
        name: "Fiji",
        flag: "🇫🇯",
        code: "FJ",
    },
    {
        id: 73,
        name: "Finland",
        flag: "🇫🇮",
        code: "FI",
    },
    {
        id: 74,
        name: "France",
        flag: "🇫🇷",
        code: "FR",
    },
    {
        id: 75,
        name: "French Guiana",
        flag: "🇬🇫",
        code: "GF",
    },
    {
        id: 76,
        name: "French Polynesia",
        flag: "🇵🇫",
        code: "PF",
    },
    {
        id: 77,
        name: "French Southern Territories",
        flag: "🇹🇫",
        code: "TF",
    },
    {
        id: 78,
        name: "Gabon",
        flag: "🇬🇦",
        code: "GA",
    },
    {
        id: 79,
        name: "Gambia",
        flag: "🇬🇲",
        code: "GM",
    },
    {
        id: 80,
        name: "Georgia",
        flag: "🇬🇪",
        code: "GE",
    },
    {
        id: 81,
        name: "Germany",
        flag: "🇩🇪",
        code: "DE",
    },
    {
        id: 82,
        name: "Ghana",
        flag: "🇬🇭",
        code: "GH",
    },
    {
        id: 83,
        name: "Gibraltar",
        flag: "🇬🇮",
        code: "GI",
    },
    {
        id: 84,
        name: "Greece",
        flag: "🇬🇷",
        code: "GR",
    },
    {
        id: 85,
        name: "Greenland",
        flag: "🇬🇱",
        code: "GL",
    },
    {
        id: 86,
        name: "Grenada",
        flag: "🇬🇩",
        code: "GD",
    },
    {
        id: 87,
        name: "Guadeloupe",
        flag: "🇬🇵",
        code: "GP",
    },
    {
        id: 88,
        name: "Guam",
        flag: "🇬🇺",
        code: "GU",
    },
    {
        id: 89,
        name: "Guatemala",
        flag: "🇬🇹",
        code: "GT",
    },
    {
        id: 90,
        name: "Guernsey",
        flag: "🇬🇬",
        code: "GG",
    },
    {
        id: 91,
        name: "Guinea",
        flag: "🇬🇳",
        code: "GN",
    },
    {
        id: 92,
        name: "Guinea-Bissau",
        flag: "🇬🇼",
        code: "GW",
    },
    {
        id: 93,
        name: "Guyana",
        flag: "🇬🇾",
        code: "GY",
    },
    {
        id: 94,
        name: "Haiti",
        flag: "🇭🇹",
        code: "HT",
    },
    {
        id: 95,
        name: "Heard Island and Mcdonald Islands",
        flag: "🇭🇲",
        code: "HM",
    },
    {
        id: 96,
        name: "Holy See (Vatican City State)",
        flag: "🇻🇦",
        code: "VA",
    },
    {
        id: 97,
        name: "Honduras",
        flag: "🇭🇳",
        code: "HN",
    },
    {
        id: 98,
        name: "Hong Kong",
        flag: "🇭🇰",
        code: "HK",
    },
    {
        id: 99,
        name: "Hungary",
        flag: "🇭🇺",
        code: "HU",
    },
    {
        id: 100,
        name: "Iceland",
        flag: "🇮🇸",
        code: "IS",
    },
    {
        id: 101,
        name: "India",
        flag: "🇮🇳",
        code: "IN",
    },
    {
        id: 102,
        name: "Indonesia",
        flag: "🇮🇩",
        code: "ID",
    },
    {
        id: 103,
        name: "Iran",
        flag: "🇮🇷",
        code: "IR",
    },
    {
        id: 104,
        name: "Iraq",
        flag: "🇮🇶",
        code: "IQ",
    },
    {
        id: 105,
        name: "Ireland",
        flag: "🇮🇪",
        code: "IE",
    },
    {
        id: 106,
        name: "Isle of Man",
        flag: "🇮🇲",
        code: "IM",
    },
    {
        id: 107,
        name: "Israel",
        flag: "🇮🇱",
        code: "IL",
    },
    {
        id: 108,
        name: "Italy",
        flag: "🇮🇹",
        code: "IT",
    },
    {
        id: 109,
        name: "Jamaica",
        flag: "🇯🇲",
        code: "JM",
    },
    {
        id: 110,
        name: "Japan",
        flag: "🇯🇵",
        code: "JP",
    },
    {
        id: 111,
        name: "Jersey",
        flag: "🇯🇪",
        code: "JE",
    },
    {
        id: 112,
        name: "Jordan",
        flag: "🇯🇴",
        code: "JO",
    },
    {
        id: 113,
        name: "Kazakhstan",
        flag: "🇰🇿",
        code: "KZ",
    },
    {
        id: 114,
        name: "Kenya",
        flag: "🇰🇪",
        code: "KE",
    },
    {
        id: 115,
        name: "Kiribati",
        flag: "🇰🇮",
        code: "KI",
    },
    {
        id: 116,
        name: "Korea",
        flag: "🇰🇵",
        code: "KP",
    },
    {
        id: 117,
        name: "Korea, (South Korea)",
        flag: "🇰🇷",
        code: "KR",
    },
    {
        id: 118,
        name: "Kosovo",
        flag: "🇽🇰",
        code: "XK",
    },
    {
        id: 119,
        name: "Kuwait",
        flag: "🇰🇼",
        code: "KW",
    },
    {
        id: 120,
        name: "Kyrgyzstan",
        flag: "🇰🇬",
        code: "KG",
    },
    {
        id: 121,
        name: "Laos",
        flag: "🇱🇦",
        code: "LA",
    },
    {
        id: 122,
        name: "Latvia",
        flag: "🇱🇻",
        code: "LV",
    },
    {
        id: 123,
        name: "Lebanon",
        flag: "🇱🇧",
        code: "LB",
    },
    {
        id: 124,
        name: "Lesotho",
        flag: "🇱🇸",
        code: "LS",
    },
    {
        id: 125,
        name: "Liberia",
        flag: "🇱🇷",
        code: "LR",
    },
    {
        id: 126,
        name: "Libyan Arab Jamahiriya",
        flag: "🇱🇾",
        code: "LY",
    },
    {
        id: 127,
        name: "Liechtenstein",
        flag: "🇱🇮",
        code: "LI",
    },
    {
        id: 128,
        name: "Lithuania",
        flag: "🇱🇹",
        code: "LT",
    },
    {
        id: 129,
        name: "Luxembourg",
        flag: "🇱🇺",
        code: "LU",
    },
    {
        id: 130,
        name: "Macao",
        flag: "🇲🇴",
        code: "MO",
    },
    {
        id: 131,
        name: "Macedonia",
        flag: "🇲🇰",
        code: "MK",
    },
    {
        id: 132,
        name: "Madagascar",
        flag: "🇲🇬",
        code: "MG",
    },
    {
        id: 133,
        name: "Malawi",
        flag: "🇲🇼",
        code: "MW",
    },
    {
        id: 134,
        name: "Malaysia",
        flag: "🇲🇾",
        code: "MY",
    },
    {
        id: 135,
        name: "Maldives",
        flag: "🇲🇻",
        code: "MV",
    },
    {
        id: 136,
        name: "Mali",
        flag: "🇲🇱",
        code: "ML",
    },
    {
        id: 137,
        name: "Malta",
        flag: "🇲🇹",
        code: "MT",
    },
    {
        id: 138,
        name: "Marshall Islands",
        flag: "🇲🇭",
        code: "MH",
    },
    {
        id: 139,
        name: "Martinique",
        flag: "🇲🇶",
        code: "MQ",
    },
    {
        id: 140,
        name: "Mauritania",
        flag: "🇲🇷",
        code: "MR",
    },
    {
        id: 141,
        name: "Mauritius",
        flag: "🇲🇺",
        code: "MU",
    },
    {
        id: 142,
        name: "Mayotte",
        flag: "🇾🇹",
        code: "YT",
    },
    {
        id: 143,
        name: "Mexico",
        flag: "🇲🇽",
        code: "MX",
    },
    {
        id: 144,
        name: "Micronesia",
        flag: "🇫🇲",
        code: "FM",
    },
    {
        id: 145,
        name: "Moldova",
        flag: "🇲🇩",
        code: "MD",
    },
    {
        id: 146,
        name: "Monaco",
        flag: "🇲🇨",
        code: "MC",
    },
    {
        id: 147,
        name: "Mongolia",
        flag: "🇲🇳",
        code: "MN",
    },
    {
        id: 148,
        name: "Montenegro",
        flag: "🇲🇪",
        code: "ME",
    },
    {
        id: 149,
        name: "Montserrat",
        flag: "🇲🇸",
        code: "MS",
    },
    {
        id: 150,
        name: "Morocco",
        flag: "🇲🇦",
        code: "MA",
    },
    {
        id: 151,
        name: "Mozambique",
        flag: "🇲🇿",
        code: "MZ",
    },
    {
        id: 152,
        name: "Myanmar",
        flag: "🇲🇲",
        code: "MM",
    },
    {
        id: 153,
        name: "Namibia",
        flag: "🇳🇦",
        code: "NA",
    },
    {
        id: 154,
        name: "Nauru",
        flag: "🇳🇷",
        code: "NR",
    },
    {
        id: 155,
        name: "Nepal",
        flag: "🇳🇵",
        code: "NP",
    },
    {
        id: 156,
        name: "Netherlands",
        flag: "🇳🇱",
        code: "NL",
    },
    {
        id: 157,
        name: "Netherlands Antilles",
        flag: "",
        code: "AN",
    },
    {
        id: 159,
        name: "New Caledonia",
        flag: "🇳🇨",
        code: "NC",
    },
    {
        id: 160,
        name: "New Zealand",
        flag: "🇳🇿",
        code: "NZ",
    },
    {
        id: 161,
        name: "Nicaragua",
        flag: "🇳🇮",
        code: "NI",
    },
    {
        id: 162,
        name: "Niger",
        flag: "🇳🇪",
        code: "NE",
    },
    {
        id: 163,
        name: "Nigeria",
        flag: "🇳🇬",
        code: "NG",
    },
    {
        id: 164,
        name: "Niue",
        flag: "🇳🇺",
        code: "NU",
    },
    {
        id: 165,
        name: "Norfolk Island",
        flag: "🇳🇫",
        code: "NF",
    },
    {
        id: 166,
        name: "Northern Mariana Islands",
        flag: "🇲🇵",
        code: "MP",
    },
    {
        id: 167,
        name: "Norway",
        flag: "🇳🇴",
        code: "NO",
    },
    {
        id: 168,
        name: "Oman",
        flag: "🇴🇲",
        code: "OM",
    },
    {
        id: 169,
        name: "Pakistan",
        flag: "🇵🇰",
        code: "PK",
    },
    {
        id: 170,
        name: "Palau",
        flag: "🇵🇼",
        code: "PW",
    },
    {
        id: 171,
        name: "Palestinian Territory",
        flag: "🇵🇸",
        code: "PS",
    },
    {
        id: 172,
        name: "Panama",
        flag: "🇵🇦",
        code: "PA",
    },
    {
        id: 173,
        name: "Papua New Guinea",
        flag: "🇵🇬",
        code: "PG",
    },
    {
        id: 174,
        name: "Paraguay",
        flag: "🇵🇾",
        code: "PY",
    },
    {
        id: 175,
        name: "Peru",
        flag: "🇵🇪",
        code: "PE",
    },
    {
        id: 176,
        name: "Philippines",
        flag: "🇵🇭",
        code: "PH",
    },
    {
        id: 177,
        name: "Pitcairn",
        flag: "🇵🇳",
        code: "PN",
    },
    {
        id: 178,
        name: "Poland",
        flag: "🇵🇱",
        code: "PL",
    },
    {
        id: 179,
        name: "Portugal",
        flag: "🇵🇹",
        code: "PT",
    },
    {
        id: 180,
        name: "Puerto Rico",
        flag: "🇵🇷",
        code: "PR",
    },
    {
        id: 181,
        name: "Qatar",
        flag: "🇶🇦",
        code: "QA",
    },
    {
        id: 182,
        name: "Romania",
        flag: "🇷🇴",
        code: "RO",
    },
    {
        id: 183,
        name: "Russia",
        flag: "🇷🇺",
        code: "RU",
    },
    {
        id: 184,
        name: "Rwanda",
        flag: "🇷🇼",
        code: "RW",
    },
    {
        id: 185,
        name: "Reunion",
        flag: "🇷🇪",
        code: "RE",
    },
    {
        id: 186,
        name: "Saint Barthelemy",
        flag: "🇧🇱",
        code: "BL",
    },
    {
        id: 187,
        name: "Saint Helena",
        flag: "🇸🇭",
        code: "SH",
    },
    {
        id: 188,
        name: "Saint Kitts and Nevis",
        flag: "🇰🇳",
        code: "KN",
    },
    {
        id: 189,
        name: "Saint Lucia",
        flag: "🇱🇨",
        code: "LC",
    },
    {
        id: 190,
        name: "Saint Martin",
        flag: "🇲🇫",
        code: "MF",
    },
    {
        id: 191,
        name: "Saint Pierre and Miquelon",
        flag: "🇵🇲",
        code: "PM",
    },
    {
        id: 192,
        name: "Saint Vincent and the Grenadines",
        flag: "🇻🇨",
        code: "VC",
    },
    {
        id: 193,
        name: "Samoa",
        flag: "🇼🇸",
        code: "WS",
    },
    {
        id: 194,
        name: "San Marino",
        flag: "🇸🇲",
        code: "SM",
    },
    {
        id: 195,
        name: "Sao Tome and Principe",
        flag: "🇸🇹",
        code: "ST",
    },
    {
        id: 196,
        name: "Saudi Arabia",
        flag: "🇸🇦",
        code: "SA",
    },
    {
        id: 197,
        name: "Senegal",
        flag: "🇸🇳",
        code: "SN",
    },
    {
        id: 198,
        name: "Serbia",
        flag: "🇷🇸",
        code: "RS",
    },
    {
        id: 199,
        name: "Seychelles",
        flag: "🇸🇨",
        code: "SC",
    },
    {
        id: 200,
        name: "Sierra Leone",
        flag: "🇸🇱",
        code: "SL",
    },
    {
        id: 201,
        name: "Singapore",
        flag: "🇸🇬",
        code: "SG",
    },
    {
        id: 202,
        name: "Slovakia",
        flag: "🇸🇰",
        code: "SK",
    },
    {
        id: 203,
        name: "Slovenia",
        flag: "🇸🇮",
        code: "SI",
    },
    {
        id: 204,
        name: "Solomon Islands",
        flag: "🇸🇧",
        code: "SB",
    },
    {
        id: 205,
        name: "Somalia",
        flag: "🇸🇴",
        code: "SO",
    },
    {
        id: 206,
        name: "South Africa",
        flag: "🇿🇦",
        code: "ZA",
    },
    {
        id: 207,
        name: "South Sudan",
        flag: "🇸🇸",
        code: "SS",
    },
    {
        id: 208,
        name: "South Georgia",
        flag: "🇬🇸",
        code: "GS",
    },
    {
        id: 209,
        name: "Spain",
        flag: "🇪🇸",
        code: "ES",
    },
    {
        id: 210,
        name: "Sri Lanka",
        flag: "🇱🇰",
        code: "LK",
    },
    {
        id: 211,
        name: "Sudan",
        flag: "🇸🇩",
        code: "SD",
    },
    {
        id: 212,
        name: "Suriname",
        flag: "🇸🇷",
        code: "SR",
    },
    {
        id: 213,
        name: "Svalbard and Jan Mayen",
        flag: "🇸🇯",
        code: "SJ",
    },
    {
        id: 214,
        name: "Swaziland",
        flag: "🇸🇿",
        code: "SZ",
    },
    {
        id: 215,
        name: "Sweden",
        flag: "🇸🇪",
        code: "SE",
    },
    {
        id: 216,
        name: "Switzerland",
        flag: "🇨🇭",
        code: "CH",

    },
    {
        id: 217,
        name: "Syrian Arab Republic",
        flag: "🇸🇾",
        code: "SY",
    },
    {
        id: 218,
        name: "Taiwan",
        flag: "🇹🇼",
        code: "TW",
    },
    {
        id: 219,
        name: "Tajikistan",
        flag: "🇹🇯",
        code: "TJ",
    },
    {
        id: 220,
        name: "Tanzania",
        flag: "🇹🇿",
        code: "TZ",
    },
    {
        id: 221,
        name: "Thailand",
        flag: "🇹🇭",
        code: "TH",
    },
    {
        id: 222,
        name: "Timor-Leste",
        flag: "🇹🇱",
        code: "TL",
    },
    {
        id: 223,
        name: "Togo",
        flag: "🇹🇬",
        code: "TG",
    },
    {
        id: 224,
        name: "Tokelau",
        flag: "🇹🇰",
        code: "TK",
    },
    {
        id: 225,
        name: "Tonga",
        flag: "🇹🇴",
        code: "TO",
    },
    {
        id: 226,
        name: "Trinidad and Tobago",
        flag: "🇹🇹",
        code: "TT",
    },
    {
        id: 227,
        name: "Tunisia",
        flag: "🇹🇳",
        code: "TN",
    },
    {
        id: 228,
        name: "Turkey",
        flag: "🇹🇷",
        code: "TR",
    },
    {
        id: 229,
        name: "Turkmenistan",
        flag: "🇹🇲",
        code: "TM",
    },
    {
        id: 230,
        name: "Turks and Caicos Islands",
        flag: "🇹🇨",
        code: "TC",
    },
    {
        id: 231,
        name: "Tuvalu",
        flag: "🇹🇻",
        code: "TV",
    },
    {
        id: 232,
        name: "Uganda",
        flag: "🇺🇬",
        code: "UG",
    },
    {
        id: 233,
        name: "Ukraine",
        flag: "🇺🇦",
        code: "UA",
    },
    {
        id: 234,
        name: "United Arab Emirates",
        flag: "🇦🇪",
        code: "AE",
    },
    {
        id: 235,
        name: "United Kingdom",
        flag: "🇬🇧",
        code: "GB",
    },
    {
        id: 236,
        name: "United States",
        flag: "🇺🇸",
        code: "US",
    },
    {
        id: 237,
        name: "Uruguay",
        flag: "🇺🇾",
        code: "UY",
    },
    {
        id: 238,
        name: "Uzbekistan",
        flag: "🇺🇿",
        code: "UZ",
    },
    {
        id: 239,
        name: "Vanuatu",
        flag: "🇻🇺",
        code: "VU",
    },
    {
        id: 240,
        name: "Venezuela",
        flag: "🇻🇪",
        code: "VE",
    },
    {
        id: 241,
        name: "Vietnam",
        flag: "🇻🇳",
        code: "VN",
    },
    {
        id: 242,
        name: "Virgin Islands, British",
        flag: "🇻🇬",
        code: "VG",
    },
    {
        id: 243,
        name: "Virgin Islands, U.S.",
        flag: "🇻🇮",
        code: "VI",
    },
    {
        id: 244,
        name: "Wallis and Futuna",
        flag: "🇼🇫",
        code: "WF",
    },
    {
        id: 245,
        name: "Yemen",
        flag: "🇾🇪",
        code: "YE",
    },
    {
        id: 246,
        name: "Zambia",
        flag: "🇿🇲",
        code: "ZM",
    },
    {
        id: 247,
        name: "Zimbabwe",
        flag: "🇿🇼",
        code: "ZW",
    }
]
